### ISSUE TITLE
Add Liberty 2.X and Sphinx in the network Modal

### ISSUE THREAD

**Issue by skundu42** [Shardeum/shardeum-dapp-boilerplate#1]
Add Liberty 2.X and Sphinx in the network Modal and set Liberty 2.X as default.

Network Details - https://docs.shardeum.org/network/endpoints

**Comment by dhruvdabhi101** [comment]
> Add Liberty 2.X and Sphinx in the network Modal and set Liberty 2.X as default.
> 
> 
> 
> Network Details - https://docs.shardeum.org/network/endpoints

I would like to contribute. Please assign issue to me. ☺️
